services:
  api01: &api
    image: app
    hostname: api01
    environment:
      - REDIS_HOST=redis
    ports:
      - "8081:8080"
    depends_on:
      - redis
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.6"
          memory: "125MB"

  api02:
    <<: *api
    hostname: api02
    ports:
      - "8082:8080"
    deploy:
      resources:
        limits:
          cpus: "0.6"
          memory: "125MB"

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    ports:
      - "9999:9999"
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "40MB"

  redis:
    image: redis:6-alpine
    hostname: redis
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: "0.20"
          memory: "60MB"

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true
