services:
  api01: &api
    image: vitortvale/rinha-2025-nestjs:latest 
    hostname: api01
    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=123
      - DB_NAME=rinha
      - REDIS_HOST=redis
    ports:
      - "8081:8080"
    depends_on:
      - db
      - redis
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.55"
          memory: "100MB"

  api02:
    <<: *api
    hostname: api02
    ports:
      - "8082:8080"
    deploy:
      resources:
        limits:
          cpus: "0.55"
          memory: "100MB"

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    ports:
      - "9999:9999"
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "40MB"

  db:
    image: postgres:17-alpine
    hostname: db
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=postgres
      - POSTGRES_DB=rinha
    ports:
      - "5433:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: "0.15"
          memory: "80MB"

  redis:
    image: redis:6-alpine
    hostname: redis
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: "0.15"
          memory: "30MB"

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true
